name: Factions
version: 1.0.0
main: fr.maxairfrance.factions.Main
api-version: 1.21
author: MaxAirFrance

commands:
  f:
    usage: /<command> [sous-commande] [arguments]
    aliases: [faction, factions]

permissions:
  factions.*:
    default: true
    children:
      factions.create: true
      factions.show: true
      factions.who: true
      factions.info: true

  factions.create:
    default: true

  factions.show:
    default: true

  factions.who:
    default: true

  factions.info:
    default: true

  factions.admin:
    default: op